[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
wget = "*"
torch = "*"
numpy = "*"
faiss-cpu = "*"
transformers = "*"
tokenizers = "*"
matplotlib = "*"
scikit-learn = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"